import type { Scratchpad, Message, AppSettings, ProviderToolDef, ChatChunk, Conversation } from '@/lib/types';
import { PuterProvider } from '@/lib/providers/puter';
import { useChatStore, getActiveMessages } from '@/stores/chat-store';
import { saveConversation } from '@/lib/storage/db';

const INTERNAL_MODEL = 'deepseek-v4-flash:free';

// Internal tools available only to the background LLM
const scratchpadTools: ProviderToolDef[] = [
  {
    name: 'update_summary',
    description: 'Update the high-level summary of the conversation.',
    parameters: {
      type: 'object',
      properties: {
        summary: { type: 'string', description: 'A concise summary of the conversation so far.' }
      },
      required: ['summary']
    }
  },
  {
    name: 'add_item',
    description: 'Add a new item to one of the scratchpad categories.',
    parameters: {
      type: 'object',
      properties: {
        category: { type: 'string', enum: ['goals', 'decisions', 'userPreferences', 'openQuestions', 'importantFacts'] },
        content: { type: 'string' },
        status: { type: 'string', enum: ['active', 'completed', 'irrelevant'] }
      },
      required: ['category', 'content']
    }
  },
  {
    name: 'update_item',
    description: 'Update an existing item in the scratchpad by ID.',
    parameters: {
      type: 'object',
      properties: {
        category: { type: 'string', enum: ['goals', 'decisions', 'userPreferences', 'openQuestions', 'importantFacts'] },
        id: { type: 'string' },
        status: { type: 'string', enum: ['active', 'completed', 'irrelevant'] },
        content: { type: 'string' }
      },
      required: ['category', 'id']
    }
  },
  {
    name: 'delete_item',
    description: 'Delete an item from the scratchpad by ID.',
    parameters: {
      type: 'object',
      properties: {
        category: { type: 'string', enum: ['goals', 'decisions', 'userPreferences', 'openQuestions', 'importantFacts'] },
        id: { type: 'string' }
      },
      required: ['category', 'id']
    }
  },
  {
    name: 'log_artifact',
    description: 'Log a new artifact that was generated by the main LLM.',
    parameters: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'The unique ID of the artifact' },
        filename: { type: 'string' },
        description: { type: 'string', description: 'What this file does or contains' }
      },
      required: ['id', 'filename', 'description']
    }
  },
  {
    name: 'log_image',
    description: 'Log a new image that was generated by the main LLM.',
    parameters: {
      type: 'object',
      properties: {
        promptUsed: { type: 'string' },
        context: { type: 'string', description: 'Why this image was requested/generated' }
      },
      required: ['promptUsed', 'context']
    }
  }
];

export function getActiveScratchpad(conversation: Conversation): Scratchpad {
  const messages = getActiveMessages(conversation);
  
  // Walk backwards up the active branch
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].scratchpad) {
      // Deep clone to avoid mutating the old snapshot directly if we are going to branch
      return JSON.parse(JSON.stringify(messages[i].scratchpad));
    }
  }

  // Return a fresh scratchpad if none exist in this branch
  return {
    messageId: '',
    conversationId: conversation.id,
    summary: '',
    goals: [],
    decisions: [],
    userPreferences: [],
    openQuestions: [],
    importantFacts: [],
    artifacts: [],
    generatedImages: [],
  };
}

export async function processScratchpadAsync(
  conversation: Conversation,
  settings: AppSettings,
  credentials: any
) {
  // Check if Puter is signed in. If not, abort gracefully.
  if (!credentials?.puter?.signedIn) {
    return;
  }

  try {
    const activeMessages = getActiveMessages(conversation);
    if (activeMessages.length === 0) return;

    let scratchpad = getActiveScratchpad(conversation);

    // Determine new messages to process
    let startIndex = 0;
    if (scratchpad.messageId) {
      const idx = activeMessages.findIndex(m => m.id === scratchpad.messageId);
      if (idx !== -1) {
        startIndex = idx + 1;
      }
    }

    const newMessages = activeMessages.slice(startIndex);
    if (newMessages.length === 0) return;

    // Convert new messages to a readable format for the internal LLM
    const chatLog = newMessages.map(m => {
      let text = '';
      m.content.forEach(c => {
        if (c.type === 'text') text += c.text;
        else if (c.type === 'tool_call') text += `\n[Tool Call: ${c.toolCall?.name}(${JSON.stringify(c.toolCall?.arguments)})]`;
        else if (c.type === 'generated_image') text += `\n[Generated Image with prompt: ${c.imagePrompt}]`;
      });
      // Detect artifacts
      const artifactRegex = /<artifact id="([^"]+)">([\s\S]*?)<\/artifact>/g;
      let match;
      while ((match = artifactRegex.exec(text)) !== null) {
         text += `\n[Created Artifact ID: ${match[1]}]`;
      }
      return `${m.role.toUpperCase()}: ${text}`;
    }).join('\n\n');

    const systemPrompt = `You are a background Memory Manager AI. Your job is to extract important information from the conversation and update the Scratchpad using the provided tools.
    
Current Scratchpad JSON:
${JSON.stringify(scratchpad, null, 2)}

You MUST use your tools to update the scratchpad based on the new messages below. If a user preference is stated, add it. If a goal is mentioned, add it. If an artifact or image is created, log it. Don't write conversational text, just use tools.`;

    const puterProvider = new PuterProvider();
    
    const stream = puterProvider.chat({
      model: INTERNAL_MODEL,
      messages: [
        { role: 'system', parts: [{ type: 'text', text: systemPrompt }] },
        { role: 'user', parts: [{ type: 'text', text: `Here are the new messages to process:\n\n${chatLog}` }] }
      ],
      tools: scratchpadTools
    });

    let dirty = false;

    // Process the stream and execute tools locally
    for await (const chunk of stream) {
      if (chunk.type === 'tool_call' && chunk.toolCall) {
        dirty = true;
        const tc = chunk.toolCall;
        const args = tc.arguments as Record<string, any>;
        
        switch (tc.name) {
          case 'update_summary':
            scratchpad.summary = args.summary;
            break;
          case 'add_item': {
            const cat = args.category as keyof Pick<Scratchpad, 'goals'|'decisions'|'userPreferences'|'openQuestions'|'importantFacts'>;
            if (scratchpad[cat]) {
              scratchpad[cat].push({
                id: Math.random().toString(36).substring(2, 8),
                content: args.content,
                status: args.status,
                updatedAt: Date.now()
              });
            }
            break;
          }
          case 'update_item': {
            const cat = args.category as keyof Pick<Scratchpad, 'goals'|'decisions'|'userPreferences'|'openQuestions'|'importantFacts'>;
            if (scratchpad[cat]) {
              const item = scratchpad[cat].find(i => i.id === args.id);
              if (item) {
                if (args.content) item.content = args.content;
                if (args.status) item.status = args.status;
                item.updatedAt = Date.now();
              }
            }
            break;
          }
          case 'delete_item': {
            const cat = args.category as keyof Pick<Scratchpad, 'goals'|'decisions'|'userPreferences'|'openQuestions'|'importantFacts'>;
            if (scratchpad[cat]) {
              scratchpad[cat] = scratchpad[cat].filter(i => i.id !== args.id);
            }
            break;
          }
          case 'log_artifact': {
            scratchpad.artifacts.push({
              id: args.id,
              filename: args.filename,
              description: args.description,
              version: 1
            });
            break;
          }
          case 'log_image': {
            scratchpad.generatedImages.push({
              promptUsed: args.promptUsed,
              context: args.context
            });
            break;
          }
        }
      }
    }

    if (dirty) {
      scratchpad.messageId = activeMessages[activeMessages.length - 1].id;
    } else {
      scratchpad.messageId = activeMessages[activeMessages.length - 1].id;
    }

    // Save the scratchpad to the active conversation's leaf message
    useChatStore.setState(state => {
      const conv = state.conversations.find(c => c.id === conversation.id);
      if (!conv) return state;

      const updatedMessages = conv.messages.map(m =>
        m.id === scratchpad.messageId ? { ...m, scratchpad } : m
      );

      const updatedConv = { ...conv, messages: updatedMessages };
      // Fire and forget save to IndexedDB
      saveConversation(updatedConv).catch(console.error);

      return {
        conversations: state.conversations.map(c => c.id === updatedConv.id ? updatedConv : c)
      };
    });

    // Log the current scratchpad content to the terminal so the user can see it
    fetch('/api/log', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        SCRATCHPAD_STATE: scratchpad
      })
    }).catch(() => {});

  } catch (err) {
    console.error('Background Scratchpad Processor failed:', err);
  }
}
